---
version: 0.0.2
loglevel: DEBUG
logpath: Logs/application.log
reverse_index:
  filename: Data/Metadata/reverse_index.csv
documents:
  - Data/Documents/cf74.xml
  - Data/Documents/cf75.xml
  - Data/Documents/cf76.xml
  - Data/Documents/cf77.xml
  - Data/Documents/cf78.xml
  - Data/Documents/cf79.xml
preprocessing:
  stemmer: true
  min_word_size: 2
path_to_vectors: Data/Metadata/vectors.csv
models_path: Data/Metadata/model
